local StreamRadioLib = StreamRadioLib

local LIBPrint = StreamRadioLib.Print
local LIBUtil = StreamRadioLib.Util

local g_mainPath = LIBUtil.GetMainDirectory("presets_test")
local g_radioColorToolName = "streamradio_gui_color_global"

-- Generated stock presets via concommand "debug_streamradio_convertpresets"
local g_settings = {
	[g_radioColorToolName] = {
		["Cold"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "0",
			["streamradio_gui_color_global_border_color_border_g"] = "0",
			["streamradio_gui_color_global_border_color_border_r"] = "0",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "173",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "64",
			["streamradio_gui_color_global_button_color_disabled_g"] = "64",
			["streamradio_gui_color_global_button_color_disabled_r"] = "64",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "0",
			["streamradio_gui_color_global_button_color_foreground_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "0",
			["streamradio_gui_color_global_button_color_foreground_r"] = "0",
			["streamradio_gui_color_global_button_color_g"] = "173",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "128",
			["streamradio_gui_color_global_button_color_hover_g"] = "128",
			["streamradio_gui_color_global_button_color_hover_r"] = "128",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "0",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "40",
			["streamradio_gui_color_global_button_color_shadow_g"] = "40",
			["streamradio_gui_color_global_button_color_shadow_r"] = "40",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "113",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "255",
			["streamradio_gui_color_global_error_color_foreground_g"] = "255",
			["streamradio_gui_color_global_error_color_foreground_r"] = "255",
			["streamradio_gui_color_global_error_color_g"] = "105",
			["streamradio_gui_color_global_error_color_r"] = "90",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "40",
			["streamradio_gui_color_global_error_color_shadow_g"] = "40",
			["streamradio_gui_color_global_error_color_shadow_r"] = "40",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "88",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "255",
			["streamradio_gui_color_global_header_color_foreground_g"] = "255",
			["streamradio_gui_color_global_header_color_foreground_r"] = "255",
			["streamradio_gui_color_global_header_color_g"] = "82",
			["streamradio_gui_color_global_header_color_r"] = "68",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "40",
			["streamradio_gui_color_global_header_color_shadow_g"] = "40",
			["streamradio_gui_color_global_header_color_shadow_r"] = "40",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "68",
			["streamradio_gui_color_global_main_color_g"] = "0",
			["streamradio_gui_color_global_main_color_r"] = "15",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "52",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "182",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "170",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "110",
			["streamradio_gui_color_global_spectrum_color_g"] = "50",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "46",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "40",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "40",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "40",
		},
		["Gray"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "2",
			["streamradio_gui_color_global_border_color_border_g"] = "2",
			["streamradio_gui_color_global_border_color_border_r"] = "2",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "173",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "52",
			["streamradio_gui_color_global_button_color_disabled_g"] = "52",
			["streamradio_gui_color_global_button_color_disabled_r"] = "52",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_foreground_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_foreground_r"] = "0",
			["streamradio_gui_color_global_button_color_g"] = "173",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "79",
			["streamradio_gui_color_global_button_color_hover_g"] = "79",
			["streamradio_gui_color_global_button_color_hover_r"] = "79",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "173",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "40",
			["streamradio_gui_color_global_button_color_shadow_g"] = "40",
			["streamradio_gui_color_global_button_color_shadow_r"] = "40",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "200",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "0",
			["streamradio_gui_color_global_error_color_foreground_g"] = "0",
			["streamradio_gui_color_global_error_color_foreground_r"] = "0",
			["streamradio_gui_color_global_error_color_g"] = "200",
			["streamradio_gui_color_global_error_color_r"] = "200",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "40",
			["streamradio_gui_color_global_error_color_shadow_g"] = "40",
			["streamradio_gui_color_global_error_color_shadow_r"] = "40",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "107",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "0",
			["streamradio_gui_color_global_header_color_foreground_g"] = "0",
			["streamradio_gui_color_global_header_color_foreground_r"] = "0",
			["streamradio_gui_color_global_header_color_g"] = "107",
			["streamradio_gui_color_global_header_color_r"] = "109",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "40",
			["streamradio_gui_color_global_header_color_shadow_g"] = "40",
			["streamradio_gui_color_global_header_color_shadow_r"] = "40",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "0",
			["streamradio_gui_color_global_main_color_g"] = "0",
			["streamradio_gui_color_global_main_color_r"] = "0",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "59",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "194",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "194",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "195",
			["streamradio_gui_color_global_spectrum_color_g"] = "59",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "59",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "40",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "40",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "40",
		},
		["Jamaica"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "0",
			["streamradio_gui_color_global_border_color_border_g"] = "0",
			["streamradio_gui_color_global_border_color_border_r"] = "0",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "0",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "0",
			["streamradio_gui_color_global_button_color_disabled_g"] = "0",
			["streamradio_gui_color_global_button_color_disabled_r"] = "43",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "161",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "161",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "161",
			["streamradio_gui_color_global_button_color_foreground_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "0",
			["streamradio_gui_color_global_button_color_foreground_r"] = "0",
			["streamradio_gui_color_global_button_color_g"] = "86",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "91",
			["streamradio_gui_color_global_button_color_hover_g"] = "91",
			["streamradio_gui_color_global_button_color_hover_r"] = "91",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "0",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "0",
			["streamradio_gui_color_global_button_color_shadow_g"] = "0",
			["streamradio_gui_color_global_button_color_shadow_r"] = "0",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "64",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "200",
			["streamradio_gui_color_global_error_color_foreground_g"] = "200",
			["streamradio_gui_color_global_error_color_foreground_r"] = "200",
			["streamradio_gui_color_global_error_color_g"] = "64",
			["streamradio_gui_color_global_error_color_r"] = "64",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "0",
			["streamradio_gui_color_global_error_color_shadow_g"] = "0",
			["streamradio_gui_color_global_error_color_shadow_r"] = "0",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "0",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "0",
			["streamradio_gui_color_global_header_color_foreground_g"] = "0",
			["streamradio_gui_color_global_header_color_foreground_r"] = "0",
			["streamradio_gui_color_global_header_color_g"] = "86",
			["streamradio_gui_color_global_header_color_r"] = "86",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "0",
			["streamradio_gui_color_global_header_color_shadow_g"] = "0",
			["streamradio_gui_color_global_header_color_shadow_r"] = "0",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "40",
			["streamradio_gui_color_global_main_color_g"] = "40",
			["streamradio_gui_color_global_main_color_r"] = "40",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "195",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "195",
			["streamradio_gui_color_global_spectrum_color_g"] = "0",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "77",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "0",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "0",
		},
		["Lava"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "0",
			["streamradio_gui_color_global_border_color_border_g"] = "0",
			["streamradio_gui_color_global_border_color_border_r"] = "104",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "84",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "64",
			["streamradio_gui_color_global_button_color_disabled_g"] = "64",
			["streamradio_gui_color_global_button_color_disabled_r"] = "64",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "130",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "200",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "200",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "200",
			["streamradio_gui_color_global_button_color_foreground_g"] = "130",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_foreground_r"] = "255",
			["streamradio_gui_color_global_button_color_g"] = "84",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "0",
			["streamradio_gui_color_global_button_color_hover_g"] = "0",
			["streamradio_gui_color_global_button_color_hover_r"] = "38",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "84",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "27",
			["streamradio_gui_color_global_button_color_shadow_g"] = "27",
			["streamradio_gui_color_global_button_color_shadow_r"] = "27",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "16",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "64",
			["streamradio_gui_color_global_error_color_foreground_g"] = "64",
			["streamradio_gui_color_global_error_color_foreground_r"] = "255",
			["streamradio_gui_color_global_error_color_g"] = "16",
			["streamradio_gui_color_global_error_color_r"] = "16",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "27",
			["streamradio_gui_color_global_error_color_shadow_g"] = "27",
			["streamradio_gui_color_global_error_color_shadow_r"] = "27",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "36",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "0",
			["streamradio_gui_color_global_header_color_foreground_g"] = "0",
			["streamradio_gui_color_global_header_color_foreground_r"] = "255",
			["streamradio_gui_color_global_header_color_g"] = "36",
			["streamradio_gui_color_global_header_color_r"] = "36",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "27",
			["streamradio_gui_color_global_header_color_shadow_g"] = "27",
			["streamradio_gui_color_global_header_color_shadow_r"] = "27",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "45",
			["streamradio_gui_color_global_main_color_g"] = "45",
			["streamradio_gui_color_global_main_color_r"] = "45",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_g"] = "14",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "54",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "27",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "27",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "27",
		},
		["Nature"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "23",
			["streamradio_gui_color_global_border_color_border_g"] = "128",
			["streamradio_gui_color_global_border_color_border_r"] = "0",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "0",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "3",
			["streamradio_gui_color_global_button_color_disabled_g"] = "36",
			["streamradio_gui_color_global_button_color_disabled_r"] = "0",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "175",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "175",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "175",
			["streamradio_gui_color_global_button_color_foreground_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "0",
			["streamradio_gui_color_global_button_color_foreground_r"] = "0",
			["streamradio_gui_color_global_button_color_g"] = "132",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "112",
			["streamradio_gui_color_global_button_color_hover_g"] = "175",
			["streamradio_gui_color_global_button_color_hover_r"] = "116",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "0",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "40",
			["streamradio_gui_color_global_button_color_shadow_g"] = "40",
			["streamradio_gui_color_global_button_color_shadow_r"] = "40",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "64",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "175",
			["streamradio_gui_color_global_error_color_foreground_g"] = "175",
			["streamradio_gui_color_global_error_color_foreground_r"] = "175",
			["streamradio_gui_color_global_error_color_g"] = "64",
			["streamradio_gui_color_global_error_color_r"] = "64",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "40",
			["streamradio_gui_color_global_error_color_shadow_g"] = "40",
			["streamradio_gui_color_global_error_color_shadow_r"] = "40",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "0",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "177",
			["streamradio_gui_color_global_header_color_foreground_g"] = "177",
			["streamradio_gui_color_global_header_color_foreground_r"] = "177",
			["streamradio_gui_color_global_header_color_g"] = "80",
			["streamradio_gui_color_global_header_color_r"] = "91",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "40",
			["streamradio_gui_color_global_header_color_shadow_g"] = "40",
			["streamradio_gui_color_global_header_color_shadow_r"] = "40",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "34",
			["streamradio_gui_color_global_main_color_g"] = "56",
			["streamradio_gui_color_global_main_color_r"] = "0",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "128",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "51",
			["streamradio_gui_color_global_spectrum_color_g"] = "0",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "0",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "40",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "40",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "40",
		},
		["Pink"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "0",
			["streamradio_gui_color_global_border_color_border_g"] = "0",
			["streamradio_gui_color_global_border_color_border_r"] = "0",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "186",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "61",
			["streamradio_gui_color_global_button_color_disabled_g"] = "61",
			["streamradio_gui_color_global_button_color_disabled_r"] = "61",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_foreground_g"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_foreground_r"] = "255",
			["streamradio_gui_color_global_button_color_g"] = "0",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "0",
			["streamradio_gui_color_global_button_color_hover_g"] = "0",
			["streamradio_gui_color_global_button_color_hover_r"] = "168",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "174",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "91",
			["streamradio_gui_color_global_button_color_shadow_g"] = "91",
			["streamradio_gui_color_global_button_color_shadow_r"] = "91",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "29",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "255",
			["streamradio_gui_color_global_error_color_foreground_g"] = "255",
			["streamradio_gui_color_global_error_color_foreground_r"] = "255",
			["streamradio_gui_color_global_error_color_g"] = "29",
			["streamradio_gui_color_global_error_color_r"] = "93",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "91",
			["streamradio_gui_color_global_error_color_shadow_g"] = "91",
			["streamradio_gui_color_global_error_color_shadow_r"] = "91",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "71",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "255",
			["streamradio_gui_color_global_header_color_foreground_g"] = "255",
			["streamradio_gui_color_global_header_color_foreground_r"] = "255",
			["streamradio_gui_color_global_header_color_g"] = "0",
			["streamradio_gui_color_global_header_color_r"] = "102",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "91",
			["streamradio_gui_color_global_header_color_shadow_g"] = "91",
			["streamradio_gui_color_global_header_color_shadow_r"] = "91",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "125",
			["streamradio_gui_color_global_main_color_g"] = "0",
			["streamradio_gui_color_global_main_color_r"] = "102",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "141",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "152",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "127",
			["streamradio_gui_color_global_spectrum_color_g"] = "141",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "141",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "91",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "91",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "91",
		},
		["Steam Original"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "68",
			["streamradio_gui_color_global_border_color_border_g"] = "88",
			["streamradio_gui_color_global_border_color_border_r"] = "76",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "68",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "61",
			["streamradio_gui_color_global_button_color_disabled_g"] = "61",
			["streamradio_gui_color_global_button_color_disabled_r"] = "61",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "149",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "120",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "120",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "120",
			["streamradio_gui_color_global_button_color_foreground_g"] = "170",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_foreground_r"] = "160",
			["streamradio_gui_color_global_button_color_g"] = "88",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "103",
			["streamradio_gui_color_global_button_color_hover_g"] = "123",
			["streamradio_gui_color_global_button_color_hover_r"] = "113",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "76",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "34",
			["streamradio_gui_color_global_button_color_shadow_g"] = "46",
			["streamradio_gui_color_global_button_color_shadow_r"] = "40",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "46",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "80",
			["streamradio_gui_color_global_error_color_foreground_g"] = "181",
			["streamradio_gui_color_global_error_color_foreground_r"] = "196",
			["streamradio_gui_color_global_error_color_g"] = "56",
			["streamradio_gui_color_global_error_color_r"] = "99",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "34",
			["streamradio_gui_color_global_error_color_shadow_g"] = "46",
			["streamradio_gui_color_global_error_color_shadow_r"] = "40",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "68",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "80",
			["streamradio_gui_color_global_header_color_foreground_g"] = "181",
			["streamradio_gui_color_global_header_color_foreground_r"] = "196",
			["streamradio_gui_color_global_header_color_g"] = "88",
			["streamradio_gui_color_global_header_color_r"] = "76",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "34",
			["streamradio_gui_color_global_header_color_shadow_g"] = "46",
			["streamradio_gui_color_global_header_color_shadow_r"] = "40",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "46",
			["streamradio_gui_color_global_main_color_g"] = "58",
			["streamradio_gui_color_global_main_color_r"] = "52",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "68",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "80",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "181",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "196",
			["streamradio_gui_color_global_spectrum_color_g"] = "88",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "76",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "34",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "46",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "40",
		},
		["Warm"] = {
			["streamradio_gui_color_global_border_color_border_a"] = "255",
			["streamradio_gui_color_global_border_color_border_b"] = "0",
			["streamradio_gui_color_global_border_color_border_g"] = "0",
			["streamradio_gui_color_global_border_color_border_r"] = "0",
			["streamradio_gui_color_global_button_color_a"] = "255",
			["streamradio_gui_color_global_button_color_b"] = "0",
			["streamradio_gui_color_global_button_color_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_disabled_b"] = "132",
			["streamradio_gui_color_global_button_color_disabled_g"] = "132",
			["streamradio_gui_color_global_button_color_disabled_r"] = "132",
			["streamradio_gui_color_global_button_color_foreground_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_b"] = "190",
			["streamradio_gui_color_global_button_color_foreground_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_disabled_b"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_g"] = "0",
			["streamradio_gui_color_global_button_color_foreground_disabled_r"] = "0",
			["streamradio_gui_color_global_button_color_foreground_g"] = "190",
			["streamradio_gui_color_global_button_color_foreground_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_foreground_hover_b"] = "190",
			["streamradio_gui_color_global_button_color_foreground_hover_g"] = "190",
			["streamradio_gui_color_global_button_color_foreground_hover_r"] = "190",
			["streamradio_gui_color_global_button_color_foreground_r"] = "190",
			["streamradio_gui_color_global_button_color_g"] = "35",
			["streamradio_gui_color_global_button_color_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_hover_b"] = "0",
			["streamradio_gui_color_global_button_color_hover_g"] = "0",
			["streamradio_gui_color_global_button_color_hover_r"] = "79",
			["streamradio_gui_color_global_button_color_icon_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_disabled_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_a"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_b"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_g"] = "255",
			["streamradio_gui_color_global_button_color_icon_hover_r"] = "255",
			["streamradio_gui_color_global_button_color_icon_r"] = "255",
			["streamradio_gui_color_global_button_color_r"] = "97",
			["streamradio_gui_color_global_button_color_shadow_a"] = "255",
			["streamradio_gui_color_global_button_color_shadow_b"] = "63",
			["streamradio_gui_color_global_button_color_shadow_g"] = "63",
			["streamradio_gui_color_global_button_color_shadow_r"] = "113",
			["streamradio_gui_color_global_cursor_color_cursor_a"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_b"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_g"] = "255",
			["streamradio_gui_color_global_cursor_color_cursor_r"] = "255",
			["streamradio_gui_color_global_error_color_a"] = "255",
			["streamradio_gui_color_global_error_color_b"] = "52",
			["streamradio_gui_color_global_error_color_foreground_a"] = "255",
			["streamradio_gui_color_global_error_color_foreground_b"] = "190",
			["streamradio_gui_color_global_error_color_foreground_g"] = "190",
			["streamradio_gui_color_global_error_color_foreground_r"] = "190",
			["streamradio_gui_color_global_error_color_g"] = "52",
			["streamradio_gui_color_global_error_color_r"] = "75",
			["streamradio_gui_color_global_error_color_shadow_a"] = "255",
			["streamradio_gui_color_global_error_color_shadow_b"] = "63",
			["streamradio_gui_color_global_error_color_shadow_g"] = "63",
			["streamradio_gui_color_global_error_color_shadow_r"] = "113",
			["streamradio_gui_color_global_header_color_a"] = "255",
			["streamradio_gui_color_global_header_color_b"] = "54",
			["streamradio_gui_color_global_header_color_foreground_a"] = "255",
			["streamradio_gui_color_global_header_color_foreground_b"] = "190",
			["streamradio_gui_color_global_header_color_foreground_g"] = "190",
			["streamradio_gui_color_global_header_color_foreground_r"] = "190",
			["streamradio_gui_color_global_header_color_g"] = "54",
			["streamradio_gui_color_global_header_color_r"] = "93",
			["streamradio_gui_color_global_header_color_shadow_a"] = "255",
			["streamradio_gui_color_global_header_color_shadow_b"] = "63",
			["streamradio_gui_color_global_header_color_shadow_g"] = "63",
			["streamradio_gui_color_global_header_color_shadow_r"] = "113",
			["streamradio_gui_color_global_main_color_a"] = "255",
			["streamradio_gui_color_global_main_color_b"] = "0",
			["streamradio_gui_color_global_main_color_g"] = "47",
			["streamradio_gui_color_global_main_color_r"] = "61",
			["streamradio_gui_color_global_spectrum_color_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_b"] = "0",
			["streamradio_gui_color_global_spectrum_color_foreground_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_foreground_b"] = "129",
			["streamradio_gui_color_global_spectrum_color_foreground_g"] = "129",
			["streamradio_gui_color_global_spectrum_color_foreground_r"] = "139",
			["streamradio_gui_color_global_spectrum_color_g"] = "46",
			["streamradio_gui_color_global_spectrum_color_icon_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_b"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_g"] = "255",
			["streamradio_gui_color_global_spectrum_color_icon_r"] = "255",
			["streamradio_gui_color_global_spectrum_color_r"] = "100",
			["streamradio_gui_color_global_spectrum_color_shadow_a"] = "255",
			["streamradio_gui_color_global_spectrum_color_shadow_b"] = "63",
			["streamradio_gui_color_global_spectrum_color_shadow_g"] = "63",
			["streamradio_gui_color_global_spectrum_color_shadow_r"] = "113",
		},
	},
}

function StreamRadioLib.GetPresets( Toolname, Setting )
	if not Toolname then return end
	if not Setting then return end
	if Toolname == "" then return end
	if Setting == "" then return end
	if not g_settings[Toolname] then return end

	return table.Copy(g_settings[Toolname][Setting])
end

function StreamRadioLib.GetPresetsTable( Toolname )
	if not Toolname then return end
	if Toolname == "" then return end

	return table.Copy(g_settings[Toolname])
end

do
	-- Preset to lua converter
	local function createpresets( ply, cmd, args )
		if not LIBUtil.IsAdminForCMD(ply) then
			return
		end

		local files = file.Find( "settings/presets/streamradio_gui_color_global/*.txt", "GAME" )

		local data = {}

		local settings = StreamRadioLib.GetPresetsTable(g_radioColorToolName)

		for _, f in ipairs( files or {} ) do
			local presetsString = file.Read( "settings/presets/streamradio_gui_color_global/" .. f, "GAME" ) or ""
			if presetsString == "" then
				continue
			end

			local presetsData = util.KeyValuesToTable(presetsString) or {}
			if table.IsEmpty(presetsData) then
				continue
			end

			local name = string.sub( f, 1, -5 )
			settings[name] = presetsData
		end

		table.insert(data, "{")
		table.insert(data, "\n")

		for name, items in SortedPairs(settings) do
			table.insert(data, "\t")
			table.insert(data, "[\"")
			table.insert(data, name)
			table.insert(data, "\"] = {")
			table.insert(data, "\n")

			for k, v in SortedPairs(items) do
				local len = #k
				local is_t = string.sub(k, len - 1) == "_t"

				if is_t then
					if name == "default" then
						v = 1
					else
						continue
					end
				end

				table.insert(data, "\t\t")
				table.insert(data, "[\"")
				table.insert(data, tostring(k or ""))
				table.insert(data, "\"] = \"")
				table.insert(data, tostring(v or ""))
				table.insert(data, "\",")
				table.insert(data, "\n")
			end

			table.insert(data, "\t")
			table.insert(data, "},")
			table.insert(data, "\n")
		end

		table.insert(data, "}")
		table.insert(data, "\n")

		data = table.concat(data, "")

		local filePath = g_mainPath .. "/streamradio_gui_color_global.txt"

		LIBUtil.CreateDirectoryForFile(filePath)

		file.Delete(filePath)
		file.Write(filePath, data)

		if file.Exists(filePath, "DATA") then
			LIBPrint.Msg(ply, "Lua formated presets for 'streamradio_gui_color_global' saved to '%s'", filePath)
		else
			LIBPrint.Msg(ply, "Could not write to '%s'", filePath)
		end
	end

	concommand.Add( "debug_streamradio_convertpresets", createpresets, nil, nil, FCVAR_CHEAT )
end

return true

